
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            America/New_York
locale:              en_US
name:		     'bored with offense'
title:               'bored with offense'
description:         'A blog about defensive computer security. '
url:                 'https://danny.mantor.org'
rss:                 feed.xml
baseurl:             ''
baseurl_posts_img:   'img/posts/'
baseurl_featured_img: 'img/hero/'
baseurl_javascripts: 'js/'
icon:                /img/icon.png # [best 300px X 300px]
disqus:              northox

author:
  name:              'Danny Fullerton'
  url:               'https://mantor.org/~northox/'
  uri:               'https://mantor.org/~northox/'
  twitter:           dfullerto
  google_plus:       northox
  linkedin:          dannyfullerton

# Server
destination:      	 ./_site
exclude:          	 [".gitignore", "CNAME", "LICENSE.md", "README.md"]
port:             	 9001

sass:
#  style: compressed
  style: expanded

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

gems: [jekyll-feed]
